services:
  db:
    image: postgres:15
    container_name: shrimp-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db:/db 
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./
      dockerfile: ./docker/dockerfile.dev
    container_name: shrimp-backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app 
    depends_on:
      - db

volumes:
  postgres_data:
