services:
  db:
    image: postgres:15
    container_name: shrimp-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db:/db 
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./
      dockerfile: ./docker/dockerfile.prod
    container_name: shrimp-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
